 #들여쓰기 제대로 하지 않으면 오류발생
 
 spring:
  profiles:
    active:
      - local # spring.profiles.active: local 프로파일을 활성화합니다.
      #스프링 부트의 프로파일은 애플리케이션 설정을 특정 환경에서만 사용 가능하도록 분리하는 방법입니다.
      #프로파일은 설정 속성의 이름이 지정된 논리적 그룹입니다.
      #서로 다른 환경(예: 개발, 테스트, 운영)을 위한 다양한 설정을 정의할 수 있습니다
      
       #local 프로파일은 프로파일 이름의 예시입니다. 보통 로컬 개발 환경에 특정한 설정을 정의할 때 사용됩니다.
       #local 프로파일이 활성화되면, 스프링 부트는 local 프로파일에 정의된 설정 속성을 로드합니다.
---
spring:
  profiles: 
    - local # spring.profiles: 이 섹션은 local 프로파일에 대한 설정을 정의합니다.
  
  mvc: 
    view:
      prefix: "/WEB-INF/views/" # spring.mvc.view.prefix: JSP 뷰 파일의 경로 접두사를 /WEB-INF/views/로 설정합니다.
      suffix: ".jsp" # spring.mvc.view.suffix: JSP 뷰 파일의 접미사를 .jsp로 설정합니다.
  
  datasource:
    url: jdbc:mysql://localhost:3306/dbtest?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  session:
    jdbc:
      initialize-schema: always
      #세션 스키마를 초기화할지 여부를 지정합니다. always로 설정하면 애플리케이션 시작 시 항상 스키마를 초기화합니다.
       # 세션 스키마를 통해 세션 데이터를 관계형 데이터베이스에 저장하여 서버 재시작 시에도 세션 상태를 유지할 수 있습니다.
      
server:
  port: 8081 # 기본 포트 넘버인 8080을 lcomputerstudy라는 프로젝트에서 사용하고 있기에 포트 넘버를 8081로 수정 (여기서 바로 수정하면됨)
  tomcat:
    uri-encoding: UTF-8
    
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      #server.servlet.encoding.charset: 서블릿의 문자 집합을 UTF-8로 설정합니다.
      #server.servlet.encoding.enabled: 서블릿 인코딩 설정을 활성화합니다.
      #server.servlet.encoding.force: 강제로 UTF-8 인코딩을 사용하게 합니다.
       
    jsp:
      init-parameters: 
        development: true 
        #JSP 초기화 매개변수를 설정합니다. development: true로 설정하면 개발 모드가 활성화되어 더 자세한 JSP 오류 메시지를 제공합니다.
        
    session: 
      timeout: 7200
  error:
     whitelabel:
      enabled: false
      #Spring Boot의 기본 화이트라벨 에러 페이지를 비활성화합니다. false로 설정하여 화이트라벨 에러 페이지를 사용하지 않게 합니다.
      
mybatis:
  type-aliases-package: com.lcomputerstudy.example.domain
  mapper-locations: mapper/**/*.xml
